// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: agent_info.proto

package pbms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InfoReporter_AgentInfoReport_FullMethodName = "/info.InfoReporter/AgentInfoReport"
)

// InfoReporterClient is the client API for InfoReporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InfoReporterClient interface {
	AgentInfoReport(ctx context.Context, in *AgentInfoReportRequest, opts ...grpc.CallOption) (*AgentInfoReportResponse, error)
}

type infoReporterClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoReporterClient(cc grpc.ClientConnInterface) InfoReporterClient {
	return &infoReporterClient{cc}
}

func (c *infoReporterClient) AgentInfoReport(ctx context.Context, in *AgentInfoReportRequest, opts ...grpc.CallOption) (*AgentInfoReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInfoReportResponse)
	err := c.cc.Invoke(ctx, InfoReporter_AgentInfoReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoReporterServer is the server API for InfoReporter service.
// All implementations must embed UnimplementedInfoReporterServer
// for forward compatibility.
type InfoReporterServer interface {
	AgentInfoReport(context.Context, *AgentInfoReportRequest) (*AgentInfoReportResponse, error)
	mustEmbedUnimplementedInfoReporterServer()
}

// UnimplementedInfoReporterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInfoReporterServer struct{}

func (UnimplementedInfoReporterServer) AgentInfoReport(context.Context, *AgentInfoReportRequest) (*AgentInfoReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AgentInfoReport not implemented")
}
func (UnimplementedInfoReporterServer) mustEmbedUnimplementedInfoReporterServer() {}
func (UnimplementedInfoReporterServer) testEmbeddedByValue()                      {}

// UnsafeInfoReporterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfoReporterServer will
// result in compilation errors.
type UnsafeInfoReporterServer interface {
	mustEmbedUnimplementedInfoReporterServer()
}

func RegisterInfoReporterServer(s grpc.ServiceRegistrar, srv InfoReporterServer) {
	// If the following call panics, it indicates UnimplementedInfoReporterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InfoReporter_ServiceDesc, srv)
}

func _InfoReporter_AgentInfoReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfoReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoReporterServer).AgentInfoReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoReporter_AgentInfoReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoReporterServer).AgentInfoReport(ctx, req.(*AgentInfoReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InfoReporter_ServiceDesc is the grpc.ServiceDesc for InfoReporter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InfoReporter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "info.InfoReporter",
	HandlerType: (*InfoReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AgentInfoReport",
			Handler:    _InfoReporter_AgentInfoReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_info.proto",
}
