// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: agent_info.proto

package pbms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentInfoReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	OsType        string                 `protobuf:"bytes,4,opt,name=osType,proto3" json:"osType,omitempty"`
	OsName        string                 `protobuf:"bytes,5,opt,name=osName,proto3" json:"osName,omitempty"`
	Sn            string                 `protobuf:"bytes,6,opt,name=sn,proto3" json:"sn,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,7,opt,name=agentVersion,proto3" json:"agentVersion,omitempty"`
	Cpu           int32                  `protobuf:"varint,8,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem           int32                  `protobuf:"varint,9,opt,name=mem,proto3" json:"mem,omitempty"`
	Disk          int32                  `protobuf:"varint,10,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfoReportRequest) Reset() {
	*x = AgentInfoReportRequest{}
	mi := &file_agent_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfoReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfoReportRequest) ProtoMessage() {}

func (x *AgentInfoReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfoReportRequest.ProtoReflect.Descriptor instead.
func (*AgentInfoReportRequest) Descriptor() ([]byte, []int) {
	return file_agent_info_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfoReportRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfoReportRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AgentInfoReportRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *AgentInfoReportRequest) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *AgentInfoReportRequest) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *AgentInfoReportRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *AgentInfoReportRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentInfoReportRequest) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *AgentInfoReportRequest) GetMem() int32 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *AgentInfoReportRequest) GetDisk() int32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

type AgentInfoReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfoReportResponse) Reset() {
	*x = AgentInfoReportResponse{}
	mi := &file_agent_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfoReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfoReportResponse) ProtoMessage() {}

func (x *AgentInfoReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfoReportResponse.ProtoReflect.Descriptor instead.
func (*AgentInfoReportResponse) Descriptor() ([]byte, []int) {
	return file_agent_info_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfoReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentInfoReportResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_agent_info_proto protoreflect.FileDescriptor

const file_agent_info_proto_rawDesc = "" +
	"\n" +
	"\x10agent_info.proto\x12\x04info\"\xf2\x01\n" +
	"\x16AgentInfoReportRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x12\x16\n" +
	"\x06osType\x18\x04 \x01(\tR\x06osType\x12\x16\n" +
	"\x06osName\x18\x05 \x01(\tR\x06osName\x12\x0e\n" +
	"\x02sn\x18\x06 \x01(\tR\x02sn\x12\"\n" +
	"\fagentVersion\x18\a \x01(\tR\fagentVersion\x12\x10\n" +
	"\x03cpu\x18\b \x01(\x05R\x03cpu\x12\x10\n" +
	"\x03mem\x18\t \x01(\x05R\x03mem\x12\x12\n" +
	"\x04disk\x18\n" +
	" \x01(\x05R\x04disk\"C\n" +
	"\x17AgentInfoReportResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2`\n" +
	"\fInfoReporter\x12P\n" +
	"\x0fAgentInfoReport\x12\x1c.info.AgentInfoReportRequest\x1a\x1d.info.AgentInfoReportResponse\"\x00B\tZ\a./;pbmsb\x06proto3"

var (
	file_agent_info_proto_rawDescOnce sync.Once
	file_agent_info_proto_rawDescData []byte
)

func file_agent_info_proto_rawDescGZIP() []byte {
	file_agent_info_proto_rawDescOnce.Do(func() {
		file_agent_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_info_proto_rawDesc), len(file_agent_info_proto_rawDesc)))
	})
	return file_agent_info_proto_rawDescData
}

var file_agent_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_info_proto_goTypes = []any{
	(*AgentInfoReportRequest)(nil),  // 0: info.AgentInfoReportRequest
	(*AgentInfoReportResponse)(nil), // 1: info.AgentInfoReportResponse
}
var file_agent_info_proto_depIdxs = []int32{
	0, // 0: info.InfoReporter.AgentInfoReport:input_type -> info.AgentInfoReportRequest
	1, // 1: info.InfoReporter.AgentInfoReport:output_type -> info.AgentInfoReportResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_info_proto_init() }
func file_agent_info_proto_init() {
	if File_agent_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_info_proto_rawDesc), len(file_agent_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_info_proto_goTypes,
		DependencyIndexes: file_agent_info_proto_depIdxs,
		MessageInfos:      file_agent_info_proto_msgTypes,
	}.Build()
	File_agent_info_proto = out.File
	file_agent_info_proto_goTypes = nil
	file_agent_info_proto_depIdxs = nil
}
