// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: agent_log.proto

package pbms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务端向 Agent 主动发起的日志拉取请求
type LogPullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogType       string                 `protobuf:"bytes,1,opt,name=logType,proto3" json:"logType,omitempty"`             // 类型: "bin" (宿主机文件) 或 "docker" (容器日志)
	LogPath       string                 `protobuf:"bytes,2,opt,name=logPath,proto3" json:"logPath,omitempty"`             // 针对 bin: 待拉取的日志文件绝对路径 (如 /data/logs/app.log)
	ContainerName string                 `protobuf:"bytes,3,opt,name=containerName,proto3" json:"containerName,omitempty"` // 针对 docker: 容器名称或 ID
	TailLines     int32                  `protobuf:"varint,4,opt,name=tailLines,proto3" json:"tailLines,omitempty"`        // 初始展示行数 (默认 200)
	Follow        bool                   `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`              // 是否持续实时尾随 (tail -f)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogPullRequest) Reset() {
	*x = LogPullRequest{}
	mi := &file_agent_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPullRequest) ProtoMessage() {}

func (x *LogPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPullRequest.ProtoReflect.Descriptor instead.
func (*LogPullRequest) Descriptor() ([]byte, []int) {
	return file_agent_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogPullRequest) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *LogPullRequest) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *LogPullRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *LogPullRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *LogPullRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

// Agent 实时向服务端回送的流式日志数据块
type LogChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`   // 日志内容块
	IsError       bool                   `protobuf:"varint,2,opt,name=isError,proto3" json:"isError,omitempty"`  // 是否发生错误
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"` // 错误提示
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunkResponse) Reset() {
	*x = LogChunkResponse{}
	mi := &file_agent_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunkResponse) ProtoMessage() {}

func (x *LogChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunkResponse.ProtoReflect.Descriptor instead.
func (*LogChunkResponse) Descriptor() ([]byte, []int) {
	return file_agent_log_proto_rawDescGZIP(), []int{1}
}

func (x *LogChunkResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *LogChunkResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *LogChunkResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_agent_log_proto protoreflect.FileDescriptor

const file_agent_log_proto_rawDesc = "" +
	"\n" +
	"\x0fagent_log.proto\x12\x03log\"\xa0\x01\n" +
	"\x0eLogPullRequest\x12\x18\n" +
	"\alogType\x18\x01 \x01(\tR\alogType\x12\x18\n" +
	"\alogPath\x18\x02 \x01(\tR\alogPath\x12$\n" +
	"\rcontainerName\x18\x03 \x01(\tR\rcontainerName\x12\x1c\n" +
	"\ttailLines\x18\x04 \x01(\x05R\ttailLines\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\"b\n" +
	"\x10LogChunkResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x18\n" +
	"\aisError\x18\x02 \x01(\bR\aisError\x12\x1a\n" +
	"\berrorMsg\x18\x03 \x01(\tR\berrorMsg2R\n" +
	"\x0fAgentLogService\x12?\n" +
	"\x0fPullRealtimeLog\x12\x13.log.LogPullRequest\x1a\x15.log.LogChunkResponse0\x01B\tZ\a./;pbmsb\x06proto3"

var (
	file_agent_log_proto_rawDescOnce sync.Once
	file_agent_log_proto_rawDescData []byte
)

func file_agent_log_proto_rawDescGZIP() []byte {
	file_agent_log_proto_rawDescOnce.Do(func() {
		file_agent_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_log_proto_rawDesc), len(file_agent_log_proto_rawDesc)))
	})
	return file_agent_log_proto_rawDescData
}

var file_agent_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_log_proto_goTypes = []any{
	(*LogPullRequest)(nil),   // 0: log.LogPullRequest
	(*LogChunkResponse)(nil), // 1: log.LogChunkResponse
}
var file_agent_log_proto_depIdxs = []int32{
	0, // 0: log.AgentLogService.PullRealtimeLog:input_type -> log.LogPullRequest
	1, // 1: log.AgentLogService.PullRealtimeLog:output_type -> log.LogChunkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_log_proto_init() }
func file_agent_log_proto_init() {
	if File_agent_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_log_proto_rawDesc), len(file_agent_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_log_proto_goTypes,
		DependencyIndexes: file_agent_log_proto_depIdxs,
		MessageInfos:      file_agent_log_proto_msgTypes,
	}.Build()
	File_agent_log_proto = out.File
	file_agent_log_proto_goTypes = nil
	file_agent_log_proto_depIdxs = nil
}
