// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: agent_log.proto

package pbms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentLogService_PullRealtimeLog_FullMethodName = "/log.AgentLogService/PullRealtimeLog"
)

// AgentLogServiceClient is the client API for AgentLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent 提供的日志拉取服务
type AgentLogServiceClient interface {
	// 服务端主动拉取: Agent 接收拉取参数后，以 Server-Streaming 形式按需持续回送日志
	PullRealtimeLog(ctx context.Context, in *LogPullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunkResponse], error)
}

type agentLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentLogServiceClient(cc grpc.ClientConnInterface) AgentLogServiceClient {
	return &agentLogServiceClient{cc}
}

func (c *agentLogServiceClient) PullRealtimeLog(ctx context.Context, in *LogPullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLogService_ServiceDesc.Streams[0], AgentLogService_PullRealtimeLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogPullRequest, LogChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLogService_PullRealtimeLogClient = grpc.ServerStreamingClient[LogChunkResponse]

// AgentLogServiceServer is the server API for AgentLogService service.
// All implementations must embed UnimplementedAgentLogServiceServer
// for forward compatibility.
//
// Agent 提供的日志拉取服务
type AgentLogServiceServer interface {
	// 服务端主动拉取: Agent 接收拉取参数后，以 Server-Streaming 形式按需持续回送日志
	PullRealtimeLog(*LogPullRequest, grpc.ServerStreamingServer[LogChunkResponse]) error
	mustEmbedUnimplementedAgentLogServiceServer()
}

// UnimplementedAgentLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentLogServiceServer struct{}

func (UnimplementedAgentLogServiceServer) PullRealtimeLog(*LogPullRequest, grpc.ServerStreamingServer[LogChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method PullRealtimeLog not implemented")
}
func (UnimplementedAgentLogServiceServer) mustEmbedUnimplementedAgentLogServiceServer() {}
func (UnimplementedAgentLogServiceServer) testEmbeddedByValue()                         {}

// UnsafeAgentLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentLogServiceServer will
// result in compilation errors.
type UnsafeAgentLogServiceServer interface {
	mustEmbedUnimplementedAgentLogServiceServer()
}

func RegisterAgentLogServiceServer(s grpc.ServiceRegistrar, srv AgentLogServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentLogService_ServiceDesc, srv)
}

func _AgentLogService_PullRealtimeLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogPullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentLogServiceServer).PullRealtimeLog(m, &grpc.GenericServerStream[LogPullRequest, LogChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLogService_PullRealtimeLogServer = grpc.ServerStreamingServer[LogChunkResponse]

// AgentLogService_ServiceDesc is the grpc.ServiceDesc for AgentLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "log.AgentLogService",
	HandlerType: (*AgentLogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullRealtimeLog",
			Handler:       _AgentLogService_PullRealtimeLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent_log.proto",
}
