// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: agent_task.proto

package pbms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单一task结果
type TaskResultOne struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //任务id
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultOne) Reset() {
	*x = TaskResultOne{}
	mi := &file_agent_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultOne) ProtoMessage() {}

func (x *TaskResultOne) ProtoReflect() protoreflect.Message {
	mi := &file_agent_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultOne.ProtoReflect.Descriptor instead.
func (*TaskResultOne) Descriptor() ([]byte, []int) {
	return file_agent_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskResultOne) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskResultOne) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResultOne) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *TaskResultOne) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

// 任务下发
type TaskAssignOne struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ScriptContext      string                 `protobuf:"bytes,2,opt,name=scriptContext,proto3" json:"scriptContext,omitempty"`
	Account            string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Args               string                 `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	ExecTimeoutSeconds int32                  `protobuf:"varint,5,opt,name=execTimeoutSeconds,proto3" json:"execTimeoutSeconds,omitempty"`
	Action             string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Lang               string                 `protobuf:"bytes,7,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskAssignOne) Reset() {
	*x = TaskAssignOne{}
	mi := &file_agent_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignOne) ProtoMessage() {}

func (x *TaskAssignOne) ProtoReflect() protoreflect.Message {
	mi := &file_agent_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignOne.ProtoReflect.Descriptor instead.
func (*TaskAssignOne) Descriptor() ([]byte, []int) {
	return file_agent_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskAssignOne) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskAssignOne) GetScriptContext() string {
	if x != nil {
		return x.ScriptContext
	}
	return ""
}

func (x *TaskAssignOne) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *TaskAssignOne) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *TaskAssignOne) GetExecTimeoutSeconds() int32 {
	if x != nil {
		return x.ExecTimeoutSeconds
	}
	return 0
}

func (x *TaskAssignOne) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TaskAssignOne) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// 结果上报
type TaskReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Results       []*TaskResultOne       `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskReportRequest) Reset() {
	*x = TaskReportRequest{}
	mi := &file_agent_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReportRequest) ProtoMessage() {}

func (x *TaskReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReportRequest.ProtoReflect.Descriptor instead.
func (*TaskReportRequest) Descriptor() ([]byte, []int) {
	return file_agent_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskReportRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TaskReportRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *TaskReportRequest) GetResults() []*TaskResultOne {
	if x != nil {
		return x.Results
	}
	return nil
}

type TaskReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tasks []*TaskAssignOne       `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// server端已经落到数据库中的任务结果
	ReceivedTaskIds []int32 `protobuf:"varint,2,rep,packed,name=ReceivedTaskIds,proto3" json:"ReceivedTaskIds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskReportResponse) Reset() {
	*x = TaskReportResponse{}
	mi := &file_agent_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReportResponse) ProtoMessage() {}

func (x *TaskReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReportResponse.ProtoReflect.Descriptor instead.
func (*TaskReportResponse) Descriptor() ([]byte, []int) {
	return file_agent_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskReportResponse) GetTasks() []*TaskAssignOne {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *TaskReportResponse) GetReceivedTaskIds() []int32 {
	if x != nil {
		return x.ReceivedTaskIds
	}
	return nil
}

var File_agent_task_proto protoreflect.FileDescriptor

const file_agent_task_proto_rawDesc = "" +
	"\n" +
	"\x10agent_task.proto\x12\x04task\"g\n" +
	"\rTaskResultOne\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\"\xcf\x01\n" +
	"\rTaskAssignOne\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12$\n" +
	"\rscriptContext\x18\x02 \x01(\tR\rscriptContext\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x12\n" +
	"\x04args\x18\x04 \x01(\tR\x04args\x12.\n" +
	"\x12execTimeoutSeconds\x18\x05 \x01(\x05R\x12execTimeoutSeconds\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x12\n" +
	"\x04lang\x18\a \x01(\tR\x04lang\"n\n" +
	"\x11TaskReportRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12-\n" +
	"\aresults\x18\x03 \x03(\v2\x13.task.TaskResultOneR\aresults\"i\n" +
	"\x12TaskReportResponse\x12)\n" +
	"\x05tasks\x18\x01 \x03(\v2\x13.task.TaskAssignOneR\x05tasks\x12(\n" +
	"\x0fReceivedTaskIds\x18\x02 \x03(\x05R\x0fReceivedTaskIds2L\n" +
	"\aJobExec\x12A\n" +
	"\n" +
	"TaskReport\x12\x17.task.TaskReportRequest\x1a\x18.task.TaskReportResponse\"\x00B\tZ\a./;pbmsb\x06proto3"

var (
	file_agent_task_proto_rawDescOnce sync.Once
	file_agent_task_proto_rawDescData []byte
)

func file_agent_task_proto_rawDescGZIP() []byte {
	file_agent_task_proto_rawDescOnce.Do(func() {
		file_agent_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_task_proto_rawDesc), len(file_agent_task_proto_rawDesc)))
	})
	return file_agent_task_proto_rawDescData
}

var file_agent_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_task_proto_goTypes = []any{
	(*TaskResultOne)(nil),      // 0: task.TaskResultOne
	(*TaskAssignOne)(nil),      // 1: task.TaskAssignOne
	(*TaskReportRequest)(nil),  // 2: task.TaskReportRequest
	(*TaskReportResponse)(nil), // 3: task.TaskReportResponse
}
var file_agent_task_proto_depIdxs = []int32{
	0, // 0: task.TaskReportRequest.results:type_name -> task.TaskResultOne
	1, // 1: task.TaskReportResponse.tasks:type_name -> task.TaskAssignOne
	2, // 2: task.JobExec.TaskReport:input_type -> task.TaskReportRequest
	3, // 3: task.JobExec.TaskReport:output_type -> task.TaskReportResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_task_proto_init() }
func file_agent_task_proto_init() {
	if File_agent_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_task_proto_rawDesc), len(file_agent_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_task_proto_goTypes,
		DependencyIndexes: file_agent_task_proto_depIdxs,
		MessageInfos:      file_agent_task_proto_msgTypes,
	}.Build()
	File_agent_task_proto = out.File
	file_agent_task_proto_goTypes = nil
	file_agent_task_proto_depIdxs = nil
}
