// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: agent_task.proto

package pbms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobExec_TaskReport_FullMethodName = "/task.JobExec/TaskReport"
)

// JobExecClient is the client API for JobExec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobExecClient interface {
	TaskReport(ctx context.Context, in *TaskReportRequest, opts ...grpc.CallOption) (*TaskReportResponse, error)
}

type jobExecClient struct {
	cc grpc.ClientConnInterface
}

func NewJobExecClient(cc grpc.ClientConnInterface) JobExecClient {
	return &jobExecClient{cc}
}

func (c *jobExecClient) TaskReport(ctx context.Context, in *TaskReportRequest, opts ...grpc.CallOption) (*TaskReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskReportResponse)
	err := c.cc.Invoke(ctx, JobExec_TaskReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobExecServer is the server API for JobExec service.
// All implementations must embed UnimplementedJobExecServer
// for forward compatibility.
type JobExecServer interface {
	TaskReport(context.Context, *TaskReportRequest) (*TaskReportResponse, error)
	mustEmbedUnimplementedJobExecServer()
}

// UnimplementedJobExecServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobExecServer struct{}

func (UnimplementedJobExecServer) TaskReport(context.Context, *TaskReportRequest) (*TaskReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskReport not implemented")
}
func (UnimplementedJobExecServer) mustEmbedUnimplementedJobExecServer() {}
func (UnimplementedJobExecServer) testEmbeddedByValue()                 {}

// UnsafeJobExecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobExecServer will
// result in compilation errors.
type UnsafeJobExecServer interface {
	mustEmbedUnimplementedJobExecServer()
}

func RegisterJobExecServer(s grpc.ServiceRegistrar, srv JobExecServer) {
	// If the following call panics, it indicates UnimplementedJobExecServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobExec_ServiceDesc, srv)
}

func _JobExec_TaskReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobExecServer).TaskReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobExec_TaskReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobExecServer).TaskReport(ctx, req.(*TaskReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobExec_ServiceDesc is the grpc.ServiceDesc for JobExec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobExec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.JobExec",
	HandlerType: (*JobExecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TaskReport",
			Handler:    _JobExec_TaskReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_task.proto",
}
